### ISSUE TITLE
already exists

### ISSUE THREAD

**Issue by adrianoesch** [vtraag/louvain-igraph#16]
just a quick note. apparently the community multilevel algorithm implemented in igraph is the louvain algorithm: https://bugs.launchpad.net/igraph/+bug/925038

**Comment by vtraag** [comment]
Thanks! I am aware of the implementation in `igraph`. But that only supports undirected modularity, while this implementation extends it to several other methods and allows for directed graphs. In addition, the framework is quite flexible so that other methods can be relatively easily implemented. Finally, it supports multiplex networks through combining several partitions (see docs for more info).
