### ISSUE TITLE
No longer builds with setuptols 58

### ISSUE THREAD

**Issue by flying-sheep** [vtraag/louvain-igraph#57]
Setuptools 58 has removed Python2 support: https://setuptools.pypa.io/en/latest/history.html#v58-0-0

I think we should run 2to3 on the codebase and add `python_requires='>=3.1'` (or so) to the metadata. that release will be able to be installed with setuptools 58.

People still using Python 2 will automatically get 0.7.0, as it will be the last version that doesn’t have `python_requires='>=3.x'` in its metadata

**Comment by vtraag** [comment]
Sorry for the long delay, I'll try to look into it next week. Just to be sure, you really *need* the `louvain` package instead of the `leidenalg` package? In principle, I hoped to no longer need to maintain `louvain` and that people would simply move to `leidenalg` instead. If this is still frequently used, I'd be happy to update it, but it's a bit more work (it requires some more extensive updates to the setup and build system), which is why I didn't pick it up yet.

**Comment by flying-sheep** [comment]
We’re only using it for backwards compatibility. Code specifying it should be able to continue to run. Our tests and examples all use `leidenalg` AFAIK.

**Comment by vtraag** [comment]
I'm closing this in favour of https://github.com/vtraag/louvain-igraph/pull/59.

**Comment by vtraag** [comment]
The `master` branch now builds correctly again, also using `setuptools>=58`. I also updated the vendored `igraph` to the latest C core. I will make a new release shortly.

**Comment by flying-sheep** [comment]
Awesome! I don’t think anyone should reasonably expect you to maintain this forever, but this version should be future proof enough now so people who need it can at least build a wheel using the legacy `setup.py bdist_wheel`.

**Comment by vtraag** [comment]
Ok, the new version 0.7.1 was just released, hopefully that should keep working for a while indeed. :)

**Comment by flying-sheep** [comment]
Thank you!
