### ISSUE TITLE
Install fails on ArchLinux

### ISSUE THREAD

**Issue by vetal4444** [vtraag/louvain-igraph#6]
Hi. 
I use ArchLinux, and can't install library. I run 
    pip  install louvain
And got this: 
```
g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-3.4/src/GraphHelper.o build/temp.linux-x86_64-3.4/src/MutableVertexPartition.o build/temp.linux-x86_64-3.4/src/pynterface.o build/temp.linux-x86_64-3.4/src/RBConfigurationVertexPartition.o build/temp.linux-x86_64-3.4/src/Optimiser.o build/temp.linux-x86_64-3.4/src/LinearResolutionParameterVertexPartition.o build/temp.linux-x86_64-3.4/src/RBERVertexPartition.o build/temp.linux-x86_64-3.4/src/SurpriseVertexPartition.o build/temp.linux-x86_64-3.4/src/ModularityVertexPartition.o build/temp.linux-x86_64-3.4/src/SignificanceVertexPartition.o build/temp.linux-x86_64-3.4/src/CPMVertexPartition.o igraphcore/lib/libigraph.a /usr/lib64/libz.a /usr/lib64/libm.a /usr/lib64/libstdc++.a -Ligraphcore/lib -L/usr/local/lib -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib -L/usr/lib -lxml2 -lpython3.4m -o build/lib.linux-x86_64-3.4/louvain/_c_louvain.cpython-34m.so
    /usr/bin/ld: /usr/lib64/libm.a(s_sin.o): relocation R_X86_64_32S against `__sincostab' can not be used when making a shared object; recompile with -fPIC
    /usr/lib64/libm.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1
```
    gcc version 4.9.2 20150304 (prerelease) (GCC)
    Python 3.4.3

Any thought why could this happen? Maybe it is distro issue or something else?

Thanks.

**Comment by vtraag** [comment]
I cannot immediately say why or how it happens. It seems that you haven't installed the `python-igraph` package before installing `louvain`, is that right? Could you try if that does compile? If that doesn't compile either, could you perhaps try to first install the `igraph` library as a shared library and then install the python package? You can download it from here http://igraph.org/c/#downloads. In that case, the package should be linked to this shared library rather than the static library, perhaps that solves the issue. There seems to be a related issue in `python-igraph` here: https://github.com/igraph/igraph/issues/598.

**Comment by vetal4444** [comment]
Thanks a lot, you was right. After install igraph package from [AUR](https://aur.archlinux.org/packages/igraph/) louvain installs successfully.

**Comment by vtraag** [comment]
OK, great, good luck using it!
