### ISSUE TITLE
module 'louvain' has no attribute 'RBConfigurationVertexPartitionWeightedLayers

### ISSUE THREAD

**Issue by samansarraf** [vtraag/louvain-igraph#60]
I am trying louvain version 0.7.1 for multilayer networks. I have installed the repo using `pip install louvain` . I am getting an error saying louvain has no attribute RBConfigurationVertexPartitionWeightedLayers . Could you please point me what version and how I need to install?
`AttributeError: module 'louvain' has no attribute 'RBConfigurationVertexPartitionWeightedLayers'`
```
import louvain
louvain.__version__
'0.7.1'
```

**Comment by vtraag** [comment]
That is correct, there is no `RBConfigurationVertexPartitionWeightedLayers`, you probably meant to use `RBConfigurationVertexPartition`. I'll close this for now, but if there's another problem, feel free to re-open and please post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to illustrate the problem.

I strongly recommend to upgrade to the [`leidenalg`](https://github.com/vtraag/leidenalg) package instead of using the `louvain` package.

**Comment by samansarraf** [comment]
Thanks for the note . How can I get this [version](https://github.com/vtraag/louvain-igraph/pull/34/files#diff-20ede19cd789debd7899cf0bb0cc3276ce0fa167f88c15457697c951d46e4c8a) ? It seems there are C++ files in that version. Thanks ! 
```
include/RBConfigurationVertexPartitionWeightedLayers.h
include/RBConfigurationVertexPartitionWeightedLayers.cpp
```

**Comment by samansarraf** [comment]
> That is correct, there is no `RBConfigurationVertexPartitionWeightedLayers`, you probably meant to use `RBConfigurationVertexPartition`. I'll close this for now, but if there's another problem, feel free to re-open and please post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to illustrate the problem.
> 
> I strongly recommend to upgrade to the [`leidenalg`](https://github.com/vtraag/leidenalg) package instead of using the `louvain` package.

Thanks for the note . How can I get this [version](https://github.com/vtraag/louvain-igraph/pull/34/files#diff-20ede19cd789debd7899cf0bb0cc3276ce0fa167f88c15457697c951d46e4c8a) ? It seems there are C++ files in that version. Thanks !

```
include/RBConfigurationVertexPartitionWeightedLayers.h
include/RBConfigurationVertexPartitionWeightedLayers.cpp
```
