### ISSUE TITLE
With 'Modularity', communities aren't stable to scale of weights

### ISSUE THREAD

**Issue by jeffalstott** [vtraag/louvain-igraph#9]
I have a fully connected, undirected graph of 121 nodes. The community structure that `louvain` returns is heavily affected by the scale of the weights. At the original weight values, all the nodes are placed in their own individual communities. But by simply multiplying all the weights by 100, we can change the community structure. Is this expected?

```
from numpy import *
import louvain
g = Graph.Full(121)
weight_sequence = rand(g.ecount())
g.es['weight'] = weight_sequence
h = louvain.find_partition(g, method='Modularity', weight='weight')
print(len(h.sizes())) ### Returns 121 communities

g.es['weight'] = weight_sequence*100
h = louvain.find_partition(g, method='Modularity', weight='weight')
print(len(h.sizes())) ### Returns 6 communities
```

I would have thought the `Modularity` method compares to a null model with the same total amount of weight on the links. Is that not the case?

**Comment by vtraag** [comment]
With random weights there is no clear community structure, only random fluctuations. Since the algorithm is stochastic you can get different results from run to run. This is especially likely to happen if communities are not well defined. 

So regardless of the multiplicative factor, you might get different results. The actual quality of a partition should be scaled with the same multiplicative factor for modularity, so that also the maximum should remain the same. You could check if the quality is indeed scaled with the same factor (which should be the case, if not there is a bug).

**Comment by jeffalstott** [comment]
"The actual quality of a partition should be scaled with the same multiplicative factor for modularity, so that also the maximum should remain the same. You could check if the quality is indeed scaled with the same factor (which should be the case, if not there is a bug)." I don't follow this part, can you explain?

Regardless, it seems like whenever I have fully-connected networks with weight values below 1 the community structure dissolves into isolated nodes:

```
g = Graph.Full(121)
g.es['weight'] = .01
h = louvain.find_partition(g, method='Modularity', weight='weight')
print(len(h.sizes())) # 121

g.es['weight'] = .99
h = louvain.find_partition(g, method='Modularity', weight='weight')
print(len(h.sizes())) # 121

g.es['weight'] = 1
h = louvain.find_partition(g, method='Modularity', weight='weight')
print(len(h.sizes())) # 1
```

**Comment by jeffalstott** [comment]
Additional note: In my original dataset (not shown so far), the weights are all below 1, but their distribution doesn't look random at all.

**Comment by vtraag** [comment]
You are right. The current version accidentally converted all weights to an integer. I'll update that as soon as possible in the overall package. It is already corrected in the development branch, so if you pull that, you should be able to use that.

**Comment by jeffalstott** [comment]
Trying to install the develop branches gives this error:

```
$python setup.py install
running install
/home/jeffrey_alstott/anaconda3/lib/python3.4/site-packages/setuptools-14.3-py3.4.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'llvmlite (0.2.2-1-gbcb15be)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
running bdist_egg
running egg_info
writing top-level names to louvain.egg-info/top_level.txt
writing requirements to louvain.egg-info/requires.txt
writing louvain.egg-info/PKG-INFO
writing dependency_links to louvain.egg-info/dependency_links.txt
reading manifest file 'louvain.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'louvain.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Build type: dynamic extension
Include path: /home/jeffrey_alstott/include/igraph
Library path: /home/jeffrey_alstott/lib
Linked dynamic libraries: igraph
Linked static libraries:
Extra compiler options:
Extra linker options:
building 'louvain._c_louvain' extension
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iinclude -I/home/jeffrey_alstott/include/igraph -I/home/jeffrey_alstott/anaconda3/include/python3.4m -c src/MutableVertexPartition.cpp -o build/temp.linux-x86_64-3.4/src/MutableVertexPartition.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iinclude -I/home/jeffrey_alstott/include/igraph -I/home/jeffrey_alstott/anaconda3/include/python3.4m -c src/RBERVertexPartition.cpp -o build/temp.linux-x86_64-3.4/src/RBERVertexPartition.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iinclude -I/home/jeffrey_alstott/include/igraph -I/home/jeffrey_alstott/anaconda3/include/python3.4m -c src/pynterface.cpp -o build/temp.linux-x86_64-3.4/src/pynterface.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
src/pynterface.cpp: In function ‘PyObject* _find_partition_multiplex(PyObject*, PyObject*, PyObject*)’:
src/pynterface.cpp:27: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:93: error: expected ‘,’ or ‘;’ before ‘PyList_SetItem’
src/pynterface.cpp:89: warning: unused variable ‘item’
src/pynterface.cpp: In function ‘PyObject* _find_partition(PyObject*, PyObject*, PyObject*)’:
src/pynterface.cpp:109: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:114: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:114: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:114: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:114: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:114: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:114: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:156: error: expected ‘,’ or ‘;’ before ‘PyList_SetItem’
src/pynterface.cpp:152: warning: unused variable ‘item’
src/pynterface.cpp: In function ‘PyObject* _quality(PyObject*, PyObject*, PyObject*)’:
src/pynterface.cpp:173: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:177: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:177: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:177: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:177: warning: deprecated conversion from string constant to ‘char*’
src/pynterface.cpp:177: warning: deprecated conversion from string constant to ‘char*’
error: command 'gcc' failed with exit status 1
```

**Comment by jeffalstott** [comment]
Should note I'm using Python 3, as that might affect things.

**Comment by vtraag** [comment]
Seems a missing semicolon at line 152 in `pynterface.cpp`. I can't change it now, but go ahead and try. If not, I'll look into it tomorrow.

**Comment by jeffalstott** [comment]
And another at line 89. Now the develop branch can build and install, running `find_partition` results in the kernel crashing.

**Comment by vtraag** [comment]
There was an exact comparison of floats, leading to problems when aggregating a graph, because the total weight is not the exact same because of round-off errors. I now allow for some tolerance (`1e-6`). I've put the fix in branch fix_weight. Can you check if that solves your issues? 

I've ran a small test as to how sensitive the detection is with respect to the weights. 
```python
G = ig.Graph.Erdos_Renyi(100, 0.1)
weights = np.logspace(1, -10, 10);
nb_comms = [];
for w in weights:
  G.es['weight'] = w;
  comms = louvain.find_partition(G, 'Modularity', weight='weight')
  nb_comms.append(len(comms));
```
![sensitivity](https://cloud.githubusercontent.com/assets/6057804/7853895/35732c08-0514-11e5-9a9e-d6442fe85ec1.png)

It seems that with weights lower than 1e-6 the detected partition starts to change. For Modularity, the weights shouldn't matter, so perhaps best to make sure the average weight is not too small.

**Comment by jeffalstott** [comment]
That appears to have worked, thanks!

By this:
"For Modularity, the weights shouldn't matter,"
I assume you mean the scale of the weights shouldn't matter, right?

For what its worth, my actual use case also has negative weights. (I'm
taking a network with only positive weights, then normalizing it in such a
way that many weights become negative. I'm then seeing how the community
structure changes.) This code should be handling the negative weights
correctly, right?

**Comment by vtraag** [comment]
Good to hear it is working! The package can deal with negative weights, but you should do some specifics in order to do so (if using Modularity). You can read a bit more here: http://www.traag.net/2015/03/02/easy-flexible-and-fast-framework-for-community-detection/#more-353. You probably want to check also what your normalisation implies exactly for the community detection then.

**Comment by jeffalstott** [comment]
Thanks! I read that, but I didn't think it applied to this case. It's not that I have two layers of a network, but one layer that has positive and negative weights. I suspect there are differences with how it handles the null model. I would expect that in the two-layer case, a null model is made for each layer. A node with 3 positive links and 4 negative links would retain 3 positive links and 4 negative links in the null model. Is that correct? I'm not sure that's the behavior I would want. Instead, I would want the node's total strength to be preserved in the null model.

"You probably want to check also what your normalisation implies exactly for the community detection then."
What do you mean by that?

**Comment by vtraag** [comment]
This becomes a bit off topic. Modularity doesn't handle negative links/weights correctly. You can check our paper http://arxiv.org/abs/0811.2329 on how modularity has difficulties with negative links. 

The problems should become quickly apparent in cases where you have sufficient negative links, because the total strength may become negative for example. That is why for negative links you need to split the graph in two layers: one positive and one negative.

If you want something else, that is possible of course. But you should make explicit what you want exactly. If you use CPM for example, then no two separate layers are needed (because the two formulations are equivalent). You could implement it in this package though. That's also what I mean with checking your normalisation. How does the normalisation work out if you simply write out Modularity? Anyway, if you want to discuss further, perhaps better over mail.

**Comment by jeffalstott** [comment]
Nice paper! Thanks!
